// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALAriaHG0yhEBf8sHROAQUjqyzo62_eWU',
    appId: '1:821255576004:web:952c27a0a2ae1a3a596c91',
    messagingSenderId: '821255576004',
    projectId: 'onze-app-905df',
    authDomain: 'onze-app-905df.firebaseapp.com',
    storageBucket: 'onze-app-905df.firebasestorage.app',
    measurementId: 'G-P77YJPFZ61',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFRU17oQyhLd-j7TGTnR3vVuywbeUZSrE',
    appId: '1:821255576004:android:e4e73620172bb47e596c91',
    messagingSenderId: '821255576004',
    projectId: 'onze-app-905df',
    storageBucket: 'onze-app-905df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO2C9fy-DMWFytSkIZIPO_-TuAmGIP9jk',
    appId: '1:821255576004:ios:91e81a1eca9f7759596c91',
    messagingSenderId: '821255576004',
    projectId: 'onze-app-905df',
    storageBucket: 'onze-app-905df.firebasestorage.app',
    iosBundleId: 'com.example.onzeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO2C9fy-DMWFytSkIZIPO_-TuAmGIP9jk',
    appId: '1:821255576004:ios:91e81a1eca9f7759596c91',
    messagingSenderId: '821255576004',
    projectId: 'onze-app-905df',
    storageBucket: 'onze-app-905df.firebasestorage.app',
    iosBundleId: 'com.example.onzeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALAriaHG0yhEBf8sHROAQUjqyzo62_eWU',
    appId: '1:821255576004:web:a5b08e6666ef7be3596c91',
    messagingSenderId: '821255576004',
    projectId: 'onze-app-905df',
    authDomain: 'onze-app-905df.firebaseapp.com',
    storageBucket: 'onze-app-905df.firebasestorage.app',
    measurementId: 'G-DVX3V8PHHW',
  );
}
